### ISSUE TITLE
Cannot read property 'Left' of undefined

### ISSUE THREAD

**Issue by gauravdhol** [basysKom/embedded-compositor#2]
Hi,

We have compiled source with Qt 6.4.1 and trying to run compositor and client.
We are able to run compositor successfully but when we are trying to run test client it is giving error 

embeddedshell.quick: virtual void QuickEmbeddedShellWindow::componentComplete() QObject(0x0)
qrc:/main.qml:11: TypeError: Cannot read property 'Left' of undefined

Can you please suggest ?

Regards,

**Comment by gauravdhol** [comment]
Hi,

libshellintegration.so link was not proper so it was returning the error 
I have corrected the link but now facing another problem

libshellintegration.so: undefined symbol: _ZN15QtWaylandClient24QWaylandShellIntegration10initializeEPNS_15QWaylandDisplayE

Can you please suggest?

**Comment by gauravdhol** [comment]
I have removed QWaylandShellIntegration::initialize(display); from  "EmbeddedShellIntegration::initialize" and it is started working

**Comment by EugenWiens** [comment]
Hi @gauravdhol,

sorry for the inconvenience, currently this project is at the beginning. If you like to use it, I purpose to wait what is happen next year. We will not try to fix the problems at the moment. 

If you like you can create a issue with your use case, so we can look at your using.

Best Regards,
Eugen

**Comment by heeen** [comment]
We are currently only targeting Qt 5.15, it is possible that this was a breaking API chnage going from Qt 5.x to Qt 6.x. thank you for noting, we may add Qt version guards in the future.

**Comment by gauravdhol** [comment]
thanks @heeen  and @EugenWiens for your input
